server:
  port: ${SERVER_PORT:9012}
  servlet:
    context-path: /financeiro-service

spring:
  application:
    name: financeiro-service
  profiles:
    active: ${ENVIRONMENT:local}
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  output:
    ansi:
      enabled: always

version:
  info:
    filename: ${project.version}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    operations-sorter: method  # Ordena os endpoints por método HTTP
    tags-sorter: alpha         # Ordena as tags em ordem alfabética
