version: '3'
services:
  indices-service:
    image: "geyson12345/financeiro-service:latest"
    container_name: ${ENVIRONMENT}-financeiro-service
    hostname: ${ENVIRONMENT}-financeiro-service
    restart: unless-stopped
    volumes:
      - ./logs:/public/logs
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_PROFILES_ACTIVE=${ENVIRONMENT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - HIKARI_CONNECTION_TIMEOUT=${HIKARI_CONNECTION_TIMEOUT}
      - HIKARI_IDLE_TIMEOUT=${HIKARI_IDLE_TIMEOUT}
      - HIKARI_MAX_LIFETIME=${HIKARI_MAX_LIFETIME}
      - HIKARI_CONNECTION_TEST_QUERY=${HIKARI_CONNECTION_TEST_QUERY}
      - HIKARI_MAXIMUM_POOL_SIZE=${HIKARI_MAXIMUM_POOL_SIZE}
      - HIKARI_MINIMUM_IDLE=${HIKARI_MINIMUM_IDLE}
      - HIKARI_INITIALIZATION_FAIL_TIMEOUT=${HIKARI_INITIALIZATION_FAIL_TIMEOUT}
      - HIKARI_ISOLATE_INTERNAL_QUERIES=${HIKARI_ISOLATE_INTERNAL_QUERIES}
      - HIKARI_VALIDATION_TIMEOUT=${HIKARI_VALIDATION_TIMEOUT}
      - HIKARI_DATASOURCE_PROPERTIES_CACHEPREPSTMTS=${HIKARI_DATASOURCE_PROPERTIES_CACHEPREPSTMTS}
      - HIKARI_DATASOURCE_PROPERTIES_PHOTOSYNTHESIZE=${HIKARI_DATASOURCE_PROPERTIES_PHOTOSYNTHESIZE}
      - HIKARI_DATASOURCE_PROPERTIES_PREPSTMTCACHESQLLIMIT=${HIKARI_DATASOURCE_PROPERTIES_PREPSTMTCACHESQLLIMIT}
      - CIRCUIT_BREAKER_SLIDING_WINDOW_SIZE=${CIRCUIT_BREAKER_SLIDING_WINDOW_SIZE}
      - CIRCUIT_BREAKER_FAILURE_RATE_THRESHOULD=${CIRCUIT_BREAKER_FAILURE_RATE_THRESHOULD}
      - CIRCUIT_BREAKER_PERMITTED_NUMBER_CALLS=${CIRCUIT_BREAKER_PERMITTED_NUMBER_CALLS}
      - CIRCUIT_BREAKER_WAIT_DURATION_IN_OPEN_STATE=${CIRCUIT_BREAKER_WAIT_DURATION_IN_OPEN_STATE}
      - CIRCUIT_BREAKER_MINIMUM_NUMBER_OF_CALLS=${CIRCUIT_BREAKER_MINIMUM_NUMBER_OF_CALLS}
      - RETRY_MAX_ATTEMPTS=${RETRY_MAX_ATTEMPTS}
      - RETRY_WAIT_DURATION=${RETRY_WAIT_DURATION}
      - LIMITER_FOR_PERIOD=${LIMITER_FOR_PERIOD}
      - LIMITER_REFRESH_PERIOD=${LIMITER_REFRESH_PERIOD}
      - LIMITER_TIMEOUT_DURATIOS=${LIMITER_TIMEOUT_DURATIOS}
      - DB_SERVER=${DB_SERVER}
      - DB_SCHEMA=${DB_SCHEMA}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    logging:
      options:
        max-size: "100m"
        max-file: "3"