CREATE TABLE LOG_AUDITORIA
(
    ID             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_ALTERACAO timestamp NOT NULL,
    USUARIO        VARCHAR(255)
);

CREATE INDEX idx_log_auditoria_data_alteracao ON LOG_AUDITORIA (DATA_ALTERACAO);
CREATE INDEX idx_log_auditoria_usuario ON LOG_AUDITORIA (USUARIO);